/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerHistorico;
import controller.ControllerMusicas;
import java.awt.Color;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import java.sql.SQLException;


/**
 *
 * @author unifybarros
 */
public class HistoricoGUI extends javax.swing.JFrame {

    /**
     * Creates new form Historico
     */
    public HistoricoGUI() {
        initComponents();
        getContentPane().setBackground(new Color(12,12,12)); 
        
        jTabbedPane1.addChangeListener(e -> {
        int index = jTabbedPane1.getSelectedIndex();
        if (index == 0) { // Aba 0 = Histórico
            try {
                ControllerHistorico controller = new ControllerHistorico(this);
                controller.carregarHistorico();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabHistorico = new javax.swing.JScrollPane();
        tabelaResultadoHistorico = new javax.swing.JTable();
        tabCurtidas = new javax.swing.JScrollPane();
        tabelaResultadoCurtidas = new javax.swing.JTable();
        tabDescurtidas = new javax.swing.JScrollPane();
        tabelaResultadoDescurtidas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaResultadoHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Título"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabHistorico.setViewportView(tabelaResultadoHistorico);

        jTabbedPane1.addTab("Histórico", tabHistorico);

        tabelaResultadoCurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Gênero", "Artista", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabCurtidas.setViewportView(tabelaResultadoCurtidas);

        jTabbedPane1.addTab("Curtidas", tabCurtidas);

        tabelaResultadoDescurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título", "Gênero", "Artista", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabDescurtidas.setViewportView(tabelaResultadoDescurtidas);

        jTabbedPane1.addTab("Descurtidas", tabDescurtidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JTable getjTable3() {
        return tabelaResultadoDescurtidas;
    }

    public void setjTable3(JTable jTable3) {
        this.tabelaResultadoDescurtidas = jTable3;
    }

    public JScrollPane getTabCurtidas() {
        return tabCurtidas;
    }

    public void setTabCurtidas(JScrollPane tabCurtidas) {
        this.tabCurtidas = tabCurtidas;
    }

    public JScrollPane getTabDescurtidas() {
        return tabDescurtidas;
    }

    public void setTabDescurtidas(JScrollPane tabDescurtidas) {
        this.tabDescurtidas = tabDescurtidas;
    }

    public JScrollPane getTabHistorico() {
        return tabHistorico;
    }

    public void setTabHistorico(JScrollPane tabHistorico) {
        this.tabHistorico = tabHistorico;
    }

    public JTable getTabelaCurtidas() {
        return tabelaResultadoCurtidas;
    }

    public void setTabelaCurtidas(JTable tabelaCurtidas) {
        this.tabelaResultadoCurtidas = tabelaCurtidas;
    }

    public JTable getTabelaResultadoHistorico() {
        return tabelaResultadoHistorico;
    }

    public void setTabelaResultadoHistorico(JTable tabelaResultadoHistorico) {
        this.tabelaResultadoHistorico = tabelaResultadoHistorico;
    }

    public JTable getTabelaResultadoCurtidas() {
        return tabelaResultadoCurtidas;
    }

    public JTable getTabelaResultadoDescurtidas() {
        return tabelaResultadoDescurtidas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoGUI().setVisible(true);
                }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane tabCurtidas;
    private javax.swing.JScrollPane tabDescurtidas;
    private javax.swing.JScrollPane tabHistorico;
    private javax.swing.JTable tabelaResultadoCurtidas;
    private javax.swing.JTable tabelaResultadoDescurtidas;
    private javax.swing.JTable tabelaResultadoHistorico;
    // End of variables declaration//GEN-END:variables
}
